/**
 * Standalone markdown report generator for Integration Audit data.
 * Extracted from IntegrationAuditService to allow reuse and testing.
 */

import { truncationSuffix, type TruncationInfo } from '@mcp-consultant-tools/core';
import type { RiskLevel } from './complexity-calculator.js';

export interface AuditReportData {
  environment: string;
  /**
   * What the report's counts are known to cover. Optional so the formatter stays usable
   * without it, but `generateAuditReport` always supplies it.
   */
  completeness?: {
    requestedMax: number;
    pluginAssemblies: TruncationInfo;
    unverified: string[];
  };
  endpointsResult: {
    endpoints: {
      name: string;
      url: string;
      contractType: string;
      authType: string;
      messageStepCount: number;
      isManaged: boolean;
    }[];
    summary: { total: number; byType: Record<string, number>; byAuthType: Record<string, number> };
  };
  webhooksResult: {
    webhooks: {
      name: string;
      endpointUrl: string | null;
      triggerEntity: string;
      triggerMessage: string;
      enabled: boolean;
    }[];
    summary: {
      total: number;
      byEntity: Record<string, number>;
      byMessage: Record<string, number>;
      enabledCount: number;
      disabledCount: number;
    };
  };
  complexityResult: {
    flows: { name: string; complexity: { score: number; riskLevel: RiskLevel; flags: { usesHttp: boolean } } }[];
    summary: {
      total: number;
      byRiskLevel: Record<RiskLevel, number>;
      averageComplexity: number;
      highRiskFlows: string[];
    };
  };
  httpFlows: { flowId: string; flowName: string; connectors: string[]; targetUrls: string[] }[];
  externalTriggerFlows: { flowId: string; flowName: string; triggerType: string }[];
  externalPlugins: { assemblyName: string; description: string | null; isolationMode: string }[];
  pluginAssemblies: { totalCount: number; assemblies: unknown[] };
  riskFactors: { factor: string; severity: RiskLevel; details: string }[];
  recommendations: string[];
  overallRisk: RiskLevel;
  requiredUrlStrings?: string[];
  environmentVariables?: {
    id: string;
    schemaName: string;
    displayName: string;
    type: string;
    currentValue?: string;
    defaultValue?: string;
    effectiveValue?: string;
    description?: string;
    isManaged: boolean;
    isSensitive: boolean;
    maskedValue?: string;
  }[];
  divergingEnvVars?: {
    variable: { schemaName: string; displayName: string; effectiveValue?: string; isSensitive: boolean };
    reason: string;
  }[];
  divergingEndpoints?: { endpoint: { name: string; url: string }; urlIssue: string }[];
  flowSecretWarnings?: {
    flowName: string;
    warnings: { actionName: string; fieldPath: string; warningType: string; message: string }[];
  }[];
  flowUrls?: {
    flowName: string;
    urls: {
      actionName: string;
      url: string;
      environmentVariable?: string;
      environmentVariableValue?: string;
      source: string;
    }[];
  }[];
  outputFormat?: 'summary' | 'full';
  ootbExclusion?: {
    endpointsExcluded: number;
    webhooksExcluded: number;
    envVarsExcluded: number;
    flowsExcluded: number;
  };
}

/**
 * Generate a complete markdown audit report from structured audit data.
 * Produces either a full report or a summary depending on `data.outputFormat`.
 */
export function generateAuditMarkdownReport(data: AuditReportData): string {
  const lines: string[] = [];
  const isSummary = data.outputFormat === 'summary';

  lines.push('# Integration Audit Report');
  lines.push('');
  lines.push(`**Generated:** ${new Date().toISOString()}`);
  lines.push(`**Environment:** ${data.environment}`);
  lines.push('');

  appendExecutiveSummary(lines, data);
  appendDivergingEndpoints(lines, data);
  appendDivergingEnvVars(lines, data);
  appendSecurityWarnings(lines, data);
  appendEnvironmentVariables(lines, data);

  appendRiskAssessment(lines, data);
  appendRecommendations(lines, data);

  if (!isSummary) {
    appendOutboundIntegrations(lines, data);
    appendInboundIntegrations(lines, data);
  }

  appendFlowComplexity(lines, data, isSummary);

  if (!isSummary) {
    appendPluginInventory(lines, data);
    appendAllUrlReferences(lines, data);
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by MCP Consultant Tools - Integration Audit*');

  return lines.join('\n');
}

// --- Section helpers ---

function appendExecutiveSummary(lines: string[], data: AuditReportData): void {
  lines.push('## Executive Summary');
  lines.push('');
  lines.push('| Metric | Count |');
  lines.push('|--------|-------|');
  lines.push(`| Power Automate Flows | ${data.complexityResult.summary.total} |`);
  lines.push(
    `| Plugin Assemblies | ${data.pluginAssemblies.totalCount}${
      data.completeness ? truncationSuffix(data.completeness.pluginAssemblies) : ''
    } |`
  );
  lines.push(`| Service Endpoints | ${data.endpointsResult.summary.total} |`);
  lines.push(`| Webhook Registrations | ${data.webhooksResult.summary.total} |`);
  lines.push(`| **Overall Risk Level** | **${data.overallRisk}** |`);
  lines.push('');

  // Add OOTB exclusion note when active
  if (data.ootbExclusion) {
    const { endpointsExcluded, webhooksExcluded, envVarsExcluded, flowsExcluded } = data.ootbExclusion;
    const totalExcluded = endpointsExcluded + webhooksExcluded + envVarsExcluded + flowsExcluded;
    if (totalExcluded > 0) {
      const parts: string[] = [];
      if (endpointsExcluded > 0) parts.push(`${endpointsExcluded} endpoints`);
      if (webhooksExcluded > 0) parts.push(`${webhooksExcluded} webhooks`);
      if (envVarsExcluded > 0) parts.push(`${envVarsExcluded} env vars`);
      if (flowsExcluded > 0) parts.push(`${flowsExcluded} flows`);
      lines.push(`> **OOTB Exclusion Active:** ${totalExcluded} Microsoft out-of-the-box items excluded`);
      lines.push(`> (${parts.join(', ')}).`);
      lines.push('> Set `excludeOotb: false` to include all items.');
      lines.push('');
    }
  }

  appendCompletenessScope(lines, data);
}

/**
 * What the counts above are and are not known to cover.
 *
 * The report caps every collection it reads, and only the plugin-assembly inventory
 * currently reports whether the cap was hit. Saying so is the point: a reader who acts on
 * a "Total Endpoints" figure needs to know that figure is a page, not a population.
 */
function appendCompletenessScope(lines: string[], data: AuditReportData): void {
  const c = data.completeness;
  if (!c) return;

  const cap = c.requestedMax === 0 ? 'uncapped' : `${c.requestedMax} rows per collection`;

  lines.push('> **Scope of these counts:** requested ' + cap + '.');

  if (c.pluginAssemblies.hasMore) {
    lines.push(
      `> The plugin-assembly inventory was **truncated** at ${c.pluginAssemblies.returnedCount}; more assemblies exist. Re-run with a higher cap, or uncapped, for the full inventory.`
    );
  } else {
    lines.push(
      `> The plugin-assembly inventory is complete at ${c.pluginAssemblies.returnedCount}.`
    );
  }

  if (c.unverified.length > 0) {
    lines.push(
      `> Completeness is **not verified** for: ${c.unverified.join(', ')}. Those counts may be a capped page rather than the population, and this report cannot currently tell you which.`
    );
  }

  lines.push('');
}

function appendDivergingEndpoints(lines: string[], data: AuditReportData): void {
  if (!data.requiredUrlStrings || !data.divergingEndpoints?.length) return;

  const patterns = data.requiredUrlStrings.map((p) => `\`${p}\``).join(', ');

  lines.push('## CRITICAL: Diverging Service Endpoints');
  lines.push('');
  lines.push('The following service endpoints do NOT match any of the required URL patterns:');
  lines.push(`- Required patterns: ${patterns}`);
  lines.push('');
  lines.push('| Name | URL | Issue |');
  lines.push('|------|-----|-------|');
  for (const d of data.divergingEndpoints) {
    lines.push(`| ${d.endpoint.name} | ${d.endpoint.url} | ${d.urlIssue} |`);
  }
  lines.push('');
}

function appendDivergingEnvVars(lines: string[], data: AuditReportData): void {
  if (!data.requiredUrlStrings || !data.divergingEnvVars?.length) return;

  const patterns = data.requiredUrlStrings.map((p) => `\`${p}\``).join(', ');

  lines.push('## WARNING: Diverging Environment Variables');
  lines.push('');
  lines.push('The following environment variables contain URLs that do NOT match any required patterns:');
  lines.push(`- Required patterns: ${patterns}`);
  lines.push('');
  lines.push('| Schema Name | Display Name | Value | Reason |');
  lines.push('|-------------|-------------|-------|--------|');
  for (const d of data.divergingEnvVars) {
    const displayValue = d.variable.isSensitive ? '***' : (d.variable.effectiveValue ?? '(none)');
    lines.push(`| ${d.variable.schemaName} | ${d.variable.displayName} | ${displayValue} | ${d.reason} |`);
  }
  lines.push('');
}

function appendSecurityWarnings(lines: string[], data: AuditReportData): void {
  if (!data.flowSecretWarnings?.length) return;

  lines.push('## Security Warnings');
  lines.push('');
  lines.push('Hardcoded secrets detected in flow definitions:');
  lines.push('');
  lines.push('| Flow | Action | Field | Warning |');
  lines.push('|------|--------|-------|---------|');
  for (const flow of data.flowSecretWarnings) {
    for (const w of flow.warnings) {
      lines.push(`| ${flow.flowName} | ${w.actionName} | ${w.fieldPath} | ${w.message} |`);
    }
  }
  lines.push('');
}

function appendEnvironmentVariables(lines: string[], data: AuditReportData): void {
  if (!data.environmentVariables?.length) return;

  const byType: Record<string, number> = {};
  let sensitiveCount = 0;
  for (const v of data.environmentVariables) {
    byType[v.type] = (byType[v.type] || 0) + 1;
    if (v.isSensitive) sensitiveCount++;
  }
  const typeBreakdown = Object.entries(byType).map(([t, c]) => `${c} ${t}`).join(', ');

  lines.push('## Environment Variables');
  lines.push('');
  lines.push(`**Total:** ${data.environmentVariables.length} (${typeBreakdown}). **Sensitive (masked):** ${sensitiveCount}`);
  lines.push('');

  if (data.outputFormat === 'summary') return;

  lines.push('| Schema Name | Display Name | Type | Effective Value | Managed |');
  lines.push('|-------------|-------------|------|-----------------|---------|');
  for (const v of data.environmentVariables) {
    const displayValue = v.isSensitive
      ? (v.maskedValue ?? '***')
      : (v.effectiveValue ?? v.defaultValue ?? '(none)');
    const managed = v.isManaged ? 'Yes' : 'No';
    lines.push(`| ${v.schemaName} | ${v.displayName} | ${v.type} | ${displayValue} | ${managed} |`);
  }
  lines.push('');
}

function appendRiskAssessment(lines: string[], data: AuditReportData): void {
  if (data.riskFactors.length === 0) return;

  lines.push('## Risk Assessment');
  lines.push('');
  lines.push('| Factor | Severity | Details |');
  lines.push('|--------|----------|---------|');
  for (const factor of data.riskFactors) {
    lines.push(`| ${factor.factor} | ${factor.severity} | ${factor.details} |`);
  }
  lines.push('');
}

function appendRecommendations(lines: string[], data: AuditReportData): void {
  if (data.recommendations.length === 0) return;

  lines.push('### Recommendations');
  lines.push('');
  for (const rec of data.recommendations) {
    lines.push(`- ${rec}`);
  }
  lines.push('');
}

function appendOutboundIntegrations(lines: string[], data: AuditReportData): void {
  lines.push('## Outbound Integrations (Data Leaving)');
  lines.push('');

  if (data.endpointsResult.endpoints.length > 0) {
    lines.push('### Service Endpoints');
    lines.push('');
    lines.push('| Name | Type | URL | Steps |');
    lines.push('|------|------|-----|-------|');
    for (const ep of data.endpointsResult.endpoints) {
      const urlDisplay = ep.url || '(internal)';
      lines.push(`| ${ep.name} | ${ep.contractType} | ${urlDisplay} | ${ep.messageStepCount} |`);
    }
    lines.push('');
  }

  if (data.httpFlows.length > 0) {
    lines.push('### Flows with HTTP/External Calls');
    lines.push('');
    for (const flow of data.httpFlows) {
      lines.push(`- **${flow.flowName}**`);
      lines.push(`  - Connectors: ${flow.connectors.join(', ')}`);
    }
    lines.push('');
  }

  appendFlowUrls(lines, data);
}

function appendFlowUrls(lines: string[], data: AuditReportData): void {
  if (!data.flowUrls?.length) return;

  lines.push('### Flow URL References');
  lines.push('');
  lines.push('| Flow | Action | URL | Source | Env Var |');
  lines.push('|------|--------|-----|--------|---------|');
  for (const flow of data.flowUrls) {
    for (const u of flow.urls) {
      const envVar = u.environmentVariable
        ? `${u.environmentVariable} (${u.environmentVariableValue ?? ''})`
        : '';
      lines.push(`| ${flow.flowName} | ${u.actionName} | ${u.url} | ${u.source} | ${envVar} |`);
    }
  }
  lines.push('');
}

function appendInboundIntegrations(lines: string[], data: AuditReportData): void {
  lines.push('## Inbound Integrations (Data Coming In)');
  lines.push('');

  if (data.webhooksResult.webhooks.length > 0) {
    lines.push('### Webhook Registrations');
    lines.push('');
    lines.push('| Name | Entity | Message | Status |');
    lines.push('|------|--------|---------|--------|');
    for (const wh of data.webhooksResult.webhooks) {
      const status = wh.enabled ? 'Enabled' : 'Disabled';
      lines.push(`| ${wh.name} | ${wh.triggerEntity} | ${wh.triggerMessage} | ${status} |`);
    }
    lines.push('');
  }

  if (data.externalTriggerFlows.length > 0) {
    lines.push('### Flows with External Triggers');
    lines.push('');
    for (const flow of data.externalTriggerFlows) {
      lines.push(`- **${flow.flowName}** (${flow.triggerType})`);
    }
    lines.push('');
  }
}

function appendFlowComplexity(lines: string[], data: AuditReportData, isSummary: boolean): void {
  lines.push('## Flow Complexity Analysis');
  lines.push('');
  lines.push('| Risk Level | Count |');
  lines.push('|------------|-------|');
  lines.push(`| Low (0-20) | ${data.complexityResult.summary.byRiskLevel.Low} |`);
  lines.push(`| Medium (21-50) | ${data.complexityResult.summary.byRiskLevel.Medium} |`);
  lines.push(`| High (51-100) | ${data.complexityResult.summary.byRiskLevel.High} |`);
  lines.push(`| Critical (>100) | ${data.complexityResult.summary.byRiskLevel.Critical} |`);
  lines.push('');
  lines.push(`**Average Complexity Score:** ${data.complexityResult.summary.averageComplexity}`);
  lines.push('');

  if (isSummary) return;

  if (data.complexityResult.summary.highRiskFlows.length > 0) {
    lines.push('### High/Critical Risk Flows');
    lines.push('');
    for (const flowName of data.complexityResult.summary.highRiskFlows) {
      const flow = data.complexityResult.flows.find((f) => f.name === flowName);
      if (flow) {
        lines.push(`- **${flowName}** - Score: ${flow.complexity.score} (${flow.complexity.riskLevel})`);
      }
    }
    lines.push('');
  }
}

function appendPluginInventory(lines: string[], data: AuditReportData): void {
  lines.push('## Plugin Inventory');
  lines.push('');
  lines.push(
    `**Total Assemblies:** ${data.pluginAssemblies.totalCount}${
      data.completeness ? truncationSuffix(data.completeness.pluginAssemblies) : ''
    }`
  );
  lines.push('');

  if (data.externalPlugins.length > 0) {
    lines.push('### Plugins with External Access');
    lines.push('');
    for (const plugin of data.externalPlugins) {
      lines.push(`- **${plugin.assemblyName}** (${plugin.isolationMode})`);
    }
    lines.push('');
  }
}

function appendAllUrlReferences(lines: string[], data: AuditReportData): void {
  const rows: { source: string; name: string; url: string }[] = [];

  // Service endpoints
  for (const ep of data.endpointsResult.endpoints) {
    if (ep.url) {
      rows.push({ source: 'Service Endpoint', name: ep.name, url: ep.url });
    }
  }

  // Flow HTTP action URLs
  if (data.flowUrls) {
    for (const flow of data.flowUrls) {
      for (const u of flow.urls) {
        rows.push({ source: `Flow: ${flow.flowName}`, name: u.actionName, url: u.url });
      }
    }
  }

  // Environment variables containing URLs (non-sensitive only)
  if (data.environmentVariables) {
    for (const v of data.environmentVariables) {
      if (!v.isSensitive && v.effectiveValue && v.effectiveValue.includes('://')) {
        rows.push({ source: 'Env Variable', name: v.schemaName, url: v.effectiveValue });
      }
    }
  }

  if (rows.length === 0) return;

  lines.push('## All URL References');
  lines.push('');
  lines.push(`**Total:** ${rows.length} URL(s) found across all integration points.`);
  lines.push('');
  lines.push('| Source | Name | URL |');
  lines.push('|--------|------|-----|');
  for (const row of rows) {
    lines.push(`| ${row.source} | ${row.name} | ${row.url} |`);
  }
  lines.push('');
}
