#!/bin/bash

# Script to split PowerPlatform into 3 packages:
# 1. powerplatform (read-only - safe for all environments)
# 2. powerplatform-customization (schema/metadata changes)
# 3. powerplatform-data (CRUD operations on records)

set -e

echo "==========================================="
echo "Splitting PowerPlatform into 3 packages"
echo "==========================================="

# Define tool categorization
READ_ONLY_TOOLS=(
  "get-entity-metadata"
  "get-entity-attributes"
  "get-entity-attribute"
  "get-entity-relationships"
  "get-global-option-set"
  "get-record"
  "query-records"
  "get-plugin-assemblies"
  "get-plugin-assembly-complete"
  "get-entity-plugin-pipeline"
  "get-plugin-trace-logs"
  "get-flows"
  "get-flow-definition"
  "get-flow-runs"
  "get-workflows"
  "get-workflow-definition"
  "get-business-rules"
  "get-business-rule"
  "get-apps"
  "get-app"
  "get-app-components"
  "get-app-sitemap"
  "get-publishers"
  "get-solutions"
  "get-forms"
  "get-views"
  "get-view-fetchxml"
  "get-web-resource"
  "get-web-resources"
  "get-webresource-dependencies"
  "get-relationship-details"
  "get-entity-customization-info"
  "validate-schema-name"
  "check-delete-eligibility"
  "check-entity-dependencies"
  "check-dependencies"
  "preview-unpublished-changes"
  "validate-solution-integrity"
)

CUSTOMIZATION_TOOLS=(
  "create-entity"
  "update-entity"
  "delete-entity"
  "publish-entity"
  "create-attribute"
  "update-attribute"
  "delete-attribute"
  "create-one-to-many-relationship"
  "create-many-to-many-relationship"
  "update-relationship"
  "delete-relationship"
  "create-global-optionset-attribute"
  "update-global-optionset"
  "add-optionset-value"
  "update-optionset-value"
  "delete-optionset-value"
  "reorder-optionset-values"
  "create-form"
  "update-form"
  "delete-form"
  "activate-form"
  "deactivate-form"
  "create-view"
  "update-view"
  "delete-view"
  "set-default-view"
  "create-web-resource"
  "update-web-resource"
  "delete-web-resource"
  "create-publisher"
  "create-solution"
  "add-solution-component"
  "remove-solution-component"
  "export-solution"
  "import-solution"
  "publish-customizations"
  "update-entity-icon"
  "add-entities-to-app"
  "validate-app"
  "publish-app"
)

DATA_CRUD_TOOLS=(
  "create-record"
  "update-record"
  "delete-record"
)

echo "Read-Only Tools: ${#READ_ONLY_TOOLS[@]}"
echo "Customization Tools: ${#CUSTOMIZATION_TOOLS[@]}"
echo "Data CRUD Tools: ${#DATA_CRUD_TOOLS[@]}"
echo ""
echo "Total: $((${#READ_ONLY_TOOLS[@]} + ${#CUSTOMIZATION_TOOLS[@]} + ${#DATA_CRUD_TOOLS[@]})) tools"
echo ""
echo "This categorization enables:"
echo "- powerplatform: Safe read-only access (production-safe)"
echo "- powerplatform-customization: Schema/metadata changes (dev/config)"
echo "- powerplatform-data: Data CRUD operations (operational)"
echo ""
echo "✅ Categorization complete - ready to create packages"
